# Generated by Django 4.0.3 on 2022-03-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('employment_date', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('information_salary', models.CharField(max_length=255)),
                ('department_one', models.CharField(max_length=255)),
                ('department_tw', models.CharField(max_length=255)),
                ('department_thr', models.CharField(max_length=255)),
                ('department_fo', models.CharField(max_length=255)),
            ],
        ),
    ]
